version: '3.9'

services:
  postgresql:
    image: postgres
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: uptime_checker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresdb:/var/lib/postgresql/data/

volumes:
  postgresdb: