//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MonitorGroup = newMonitorGroupTable("public", "monitor_group", "")

type monitorGroupTable struct {
	postgres.Table

	//Columns
	ID             postgres.ColumnInteger
	Name           postgres.ColumnString
	OrganizationID postgres.ColumnInteger
	InsertedAt     postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type MonitorGroupTable struct {
	monitorGroupTable

	EXCLUDED monitorGroupTable
}

// AS creates new MonitorGroupTable with assigned alias
func (a MonitorGroupTable) AS(alias string) *MonitorGroupTable {
	return newMonitorGroupTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MonitorGroupTable with assigned schema name
func (a MonitorGroupTable) FromSchema(schemaName string) *MonitorGroupTable {
	return newMonitorGroupTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MonitorGroupTable with assigned table prefix
func (a MonitorGroupTable) WithPrefix(prefix string) *MonitorGroupTable {
	return newMonitorGroupTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MonitorGroupTable with assigned table suffix
func (a MonitorGroupTable) WithSuffix(suffix string) *MonitorGroupTable {
	return newMonitorGroupTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMonitorGroupTable(schemaName, tableName, alias string) *MonitorGroupTable {
	return &MonitorGroupTable{
		monitorGroupTable: newMonitorGroupTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newMonitorGroupTableImpl("", "excluded", ""),
	}
}

func newMonitorGroupTableImpl(schemaName, tableName, alias string) monitorGroupTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		NameColumn           = postgres.StringColumn("name")
		OrganizationIDColumn = postgres.IntegerColumn("organization_id")
		InsertedAtColumn     = postgres.TimestampColumn("inserted_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{IDColumn, NameColumn, OrganizationIDColumn, InsertedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{NameColumn, OrganizationIDColumn, InsertedAtColumn, UpdatedAtColumn}
	)

	return monitorGroupTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		Name:           NameColumn,
		OrganizationID: OrganizationIDColumn,
		InsertedAt:     InsertedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
