//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Check struct {
	ID             int64 `sql:"primary_key"`
	Body           *string
	Traces         *string
	Headers        *string
	StatusCode     *int32
	ContentSize    *int32
	ContentType    *int32
	Duration       *int32
	Success        bool
	RegionID       *int64
	MonitorID      *int64
	OrganizationID *int64
	InsertedAt     time.Time
	UpdatedAt      time.Time
}
