//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type DailyReport struct {
	ID               int64 `sql:"primary_key"`
	SuccessfulChecks *int32
	ErrorChecks      *int32
	Downtime         *int32
	Date             *time.Time
	MonitorID        *int64
	OrganizationID   *int64
	InsertedAt       time.Time
	UpdatedAt        time.Time
}
