//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ErrorLog struct {
	ID            int64 `sql:"primary_key"`
	Text          *string
	Type          *int32
	ScreenshotURL *string
	CheckID       int64
	MonitorID     int64
	AssertionID   *int64
	InsertedAt    time.Time
	UpdatedAt     time.Time
}
