//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Invitation struct {
	ID                int64 `sql:"primary_key"`
	Email             string
	Code              string
	ExpiresAt         time.Time
	NotificationCount *int32
	InvitedByUserID   *int64
	RoleID            *int64
	OrganizationID    *int64
	InsertedAt        time.Time
	UpdatedAt         time.Time
}
