//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Job struct {
	ID         int64 `sql:"primary_key"`
	Status     int32
	On         bool
	Name       string
	Interval   *int32
	LastRanAt  *time.Time
	NextRunAt  *time.Time
	Recurring  bool
	InsertedAt time.Time
	UpdatedAt  time.Time
}
