//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type MonitorRegion struct {
	ID            int64 `sql:"primary_key"`
	Down          *bool
	LastCheckedAt *time.Time
	MonitorID     *int64
	RegionID      *int64
	InsertedAt    time.Time
	UpdatedAt     time.Time
}
