//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type OrganizationUser struct {
	ID             int64 `sql:"primary_key"`
	Status         int32
	RoleID         int64
	UserID         int64
	OrganizationID int64
	InsertedAt     time.Time
	UpdatedAt      time.Time
}
