//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ProductFeature struct {
	ID         int64 `sql:"primary_key"`
	Count      int32
	ProductID  int64
	FeatureID  int64
	InsertedAt time.Time
	UpdatedAt  time.Time
}
