//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Subscription struct {
	ID                 int64 `sql:"primary_key"`
	Status             *int32
	StartsAt           *time.Time
	ExpiresAt          *time.Time
	CanceledAt         *time.Time
	IsTrial            bool
	ExternalID         *string
	ExternalCustomerID *string
	PlanID             int64
	ProductID          int64
	OrganizationID     int64
	InsertedAt         time.Time
	UpdatedAt          time.Time
}
