//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type UserContact struct {
	ID                        int64 `sql:"primary_key"`
	Email                     *string
	Number                    *string
	Mode                      *int32
	DeviceID                  *string
	VerificationCode          *string
	VerificationCodeExpiresAt *time.Time
	Verified                  bool
	Subscribed                bool
	BounceCount               *int32
	UserID                    *int64
	InsertedAt                time.Time
	UpdatedAt                 time.Time
}
